### PR TITLE
[native] make sure ParserError's line is zero-indexed

### LINKED ISSUE #678: IndexError when `str(e)` for ParserSyntaxError with native parser
It seems that for the native parser, it's unable to render the exception info like it's used to when using the Python parser.

## Reproduction steps

```python
# Python 3.10.4 (main, Apr  1 2022, 13:25:48) [Clang 13.0.1 ] on darwin
# Type "help", "copyright", "credits" or "license" for more information.
import libcst as cst
expr = "print('hello'\n"
try:
    cst.parse_expression(expr)
except cst.ParserSyntaxError as err:
    print(err)

# Syntax Error @ 2:1.
# Incomplete input. Encountered end of file (EOF), but expected ')'.
#
# print('hello'
#              ^

import os
os.environ["LIBCST_PARSER_TYPE"] = "native"
try:
    cst.parse_expression(expr)
except cst.ParserSyntaxError as err:
    print(err)

# Traceback (most recent call last):
#  File "<stdin>", line 2, in <module>
#  File "/Users/dhruv/projects/remove-print-statements/.venv/lib/python3.10/site-packages/libcst/_parser/entrypoints.py", line 160, in parse_expression
#    result = _parse(
#  File "/Users/dhruv/projects/remove-print-statements/.venv/lib/python3.10/site-packages/libcst/_parser/entrypoints.py", line 55, in _parse
#    return parse(source_str)
# libcst._exceptions.ParserSyntaxError: <exception str() failed>
#
# During handling of the above exception, another exception occurred:
#
# Traceback (most recent call last):
#  File "<stdin>", line 4, in <module>
#  File "/Users/dhruv/projects/remove-print-statements/.venv/lib/python3.10/site-packages/libcst/_exceptions.py", line 154, in __str__
#    context = self.context
#  File "/Users/dhruv/projects/remove-print-statements/.venv/lib/python3.10/site-packages/libcst/_exceptions.py", line 179, in context
#    displayed_column = self.editor_column
#  File "/Users/dhruv/projects/remove-print-statements/.venv/lib/python3.10/site-packages/libcst/_exceptions.py", line 222, in editor_column
#    prefix_str = self._lines[self.raw_line - 1][: self.raw_column]
# IndexError: list index out of range
```

## Information

- `libcst` version: `0.4.1`
- Python version: `3.10.4`
- OS: macOS Monterey 12.3.1

### PR DESCRIPTION
**Pull request by zsol**
## Summary

The `ParserError` raised from the peg parser has 0-based line indices, but its `__str__` implementation expects it to be 1-based. This causes exceptions while trying to render the `ParserError` exception.

Fixes #678.

## Test Plan
Added tests to verify `str()` doesn't blow up.

### CODE REVIEW

File: native/libcst/src/parser/errors.rs [hunk 1]
```diff
@@ -49,16 +49,20 @@ mod py_error {
...
+                if line + 1 > lines.len() {
+                    line = lines.len() - 1;
+                    col = 0;
+                }
                 let kwargs = [
                     ("message", e.to_string().into_py(py)),
                     ("lines", lines.into_py(py)),
-                    ("raw_line", line.into_py(py)),
+                    ("raw_line", (line + 1).into_py(py)),
                     ("raw_column", col.into_py(py)),
```
Comment (lpetre) [inline native/libcst/src/parser/errors.rs:66]: Is column zero or one based?

**Review by lpetre — APPROVED** [review]
Looks good to me. Please clarify about raw_column

**Comment by zsol** [comment]
should be 0-indexed https://github.com/Instagram/LibCST/blob/6e0c63ae9cb97f3cf40143313783d05e8c699e35/libcst/_exceptions.py#L115-L117
